export const MEALS_DATA = [
  {
    id: 'indian3',
    name: 'Chicken Tikka',
    category: 'Indian',
    image: 'chicken-tikka.jpeg',
    price: 13,
  },
  {
    id: 'Thai1',
    name: 'Kai Med Mamoung',
    category: 'Thai',
    image: 'kai-med-mamoung.jpeg',
    price: 17,
  },
  {
    id: 'Thai3',
    name: 'Keang Khieuw Waan Kai',
    category: 'Thai',
    image: 'keang-khieuw-waan-kai.jpeg',
    price: 16.333,
  },
  {
    id: 'FastFood2',
    name: 'Double Big Tasty',
    category: 'Fast food',
    image: 'double-big-tasty.jpeg',
    price: 21.75,
  },
  {
    id: 'FastFood10',
    name: 'Veggie Mc Chicken',
    category: 'Fast food',
    image: 'veggie-mcchicken.jpeg',
    price: 19.55,
  },
  {
    id: 'Italian7',
    name: 'Pollo Piñata',
    category: 'Italian',
    image: 'pollo-piñata.png',
    price: 16.45,
  },
  {
    id: 'indian7',
    name: 'Saag Paneer',
    category: 'Indian',
    image: 'saag-paneer.jpeg',
    price: 17.5,
  },
  {
    id: 'indian5',
    name: 'Dal Makhni',
    category: 'Indian',
    image: 'dal-makhni.jpeg',
    price: 18.9,
  },
  {
    id: 'Sushi9',
    name: 'Sushi Sashimi',
    category: 'Sushi',
    image: 'sushi-sashimi.jpeg',
    price: 16.88,
  },
  {
    id: 'Drink7',
    name: 'Sisi Can 330mL',
    category: 'Drink',
    image: 'sisi-can-330ml.jpeg',
    price: 6.01,
  },
  {
    id: 'Salad5',
    name: 'Side Salad',
    category: 'Salad',
    image: 'side-salad.jpeg',
    price: 9.89,
  },
  {
    id: 'Pizza1',
    name: 'Pizza Boscaiola',
    category: 'Pizza',
    image: 'pizza-boscaiola.jpeg',
    price: 13.5,
  },
  {
    id: 'Pizza5',
    name: 'Pizza Marinara',
    category: 'Pizza',
    image: 'pizza-marinara.jpeg',
    price: 15.5,
  },
  {
    id: 'Salad4',
    name: 'Grilled Chicken Salad',
    category: 'Salad',
    image: 'grilled-chicken-salad.jpeg',
    price: 15.9,
  },
  {
    id: 'FastFood1',
    name: 'Big Mac',
    category: 'Fast food',
    image: 'big-mac.jpeg',
    price: 19.5,
  },
  {
    id: 'Pizza12',
    name: 'Pizza Zucca',
    category: 'Pizza',
    image: 'pizza-zucca.jpeg',
    price: 17.8,
  },
  {
    id: 'Sushi1',
    name: 'Combi Menu 708',
    category: 'Sushi',
    image: 'combi-menu-708.jpeg',
    price: 31.22,
  },
  {
    id: 'Italian8',
    name: 'Quesadilla',
    category: 'Italian',
    image: 'quesadilla.png',
    price: 12.21,
  },
  {
    id: 'indian9',
    name: 'Vegetable Biryani',
    category: 'Indian',
    image: 'vegetable-biryani.jpeg',
    price: 19,
  },
  {
    id: 'FastFood5',
    name: 'Homestyle Crispy Chicken Honey Mustard',
    category: 'Fast food',
    image: 'homestyle-crispy-chicken-honey-mustard.jpeg',
    price: 18.2,
  },
  {
    id: 'Thai2',
    name: 'Kai Pad Ped',
    category: 'Thai',
    image: 'kai-pad-ped.jpeg',
    price: 15.5,
  },
  {
    id: 'Sushi2',
    name: 'Combi Menu 713',
    category: 'Sushi',
    image: 'combi-menu-713.jpeg',
    price: 39.98,
  },
  {
    id: 'Sushi12',
    name: 'Zushi Delight',
    category: 'Sushi',
    image: 'zushi-delight.jpeg',
    price: 30.55,
  },
  {
    id: 'Drink2',
    name: 'Coca Cola 0.5L',
    category: 'Drink',
    image: 'coca-cola-0.5l.jpeg',
    price: 5.1,
  },
  {
    id: 'FastFood4',
    name: 'Filet O Fish',
    category: 'Fast food',
    image: 'filet-o-fish.jpeg',
    price: 17,
  },
  {
    id: 'indian8',
    name: 'Tandoori Mix Grill',
    category: 'Indian',
    image: 'tandoori-mix-grill.jpeg',
    price: 16.33,
  },
  {
    id: 'Mexican2',
    name: 'Chipotle Tuna',
    category: 'Mexican',
    image: 'chipotle-tuna.jpeg',
    price: 14.991,
  },
  {
    id: 'Sushi5',
    name: 'Maki Mix',
    category: 'Sushi',
    image: 'maki-mix.jpeg',
    price: 23.511,
  },
  {
    id: 'Drink1',
    name: '7 Up Can 330mL',
    category: 'Drink',
    image: '7-up-can-330ml.jpeg',
    price: 4.36,
  },
  {
    id: 'Salad2',
    name: 'Couscous Salade Harissa Kip',
    category: 'Salad',
    image: 'couscous-salade-harissa-kip.jpeg',
    price: 11.25,
  },
  {
    id: 'Italian11',
    name: 'Yuca Frita',
    category: 'Italian',
    image: 'yuca-frita.png',
    price: 16.5,
  },
  {
    id: 'FastFood3',
    name: 'Double Quarter Pounder',
    category: 'Fast food',
    image: 'double-quarter-pounder.jpeg',
    price: 19.5,
  },
  {
    id: 'Thai11',
    name: 'Zoete Thaise Chilisaus',
    category: 'Thai',
    image: 'zoete-thaise-chilisaus.jpeg',
    price: 14.3,
  },
  {
    id: 'Pizza6',
    name: 'Pizza Pachino',
    category: 'Pizza',
    image: 'pizza-pachino.jpeg',
    price: 14.9,
  },
  {
    id: 'indian4',
    name: 'Chicken Tikka Masala',
    category: 'Indian',
    image: 'chicken-tikka-masala.jpeg',
    price: 12,
  },
  {
    id: 'FastFood8',
    name: 'Single Big Tasty',
    category: 'Fast food',
    image: 'single-big-tasty.jpeg',
    price: 17.5,
  },
  {
    id: 'Pizza11',
    name: 'Pizza Vegana',
    category: 'Pizza',
    image: 'pizza-vegana.jpeg',
    price: 19.99,
  },
  {
    id: 'Thai9',
    name: "Vegetarische Loempia's",
    category: 'Thai',
    image: "vegetarische-loempia's.jpeg",
    price: 15.059,
  },
  {
    id: 'Drink5',
    name: 'Pepsi Can 330mL',
    category: 'Drink',
    image: 'pepsi-can-330ml.jpeg',
    price: 4.99,
  },
  {
    id: 'Mexican3',
    name: 'Classic Chicken Sandwarma Wrap',
    category: 'Mexican',
    image: 'classic-chicken-sandwarma-wrap.jpeg',
    price: 21,
  },
  {
    id: 'Drink6',
    name: 'Pepsi Max Can 330mL',
    category: 'Drink',
    image: 'pepsi-max-can-330ml.jpeg',
    price: 4.99,
  },
  {
    id: 'Italian5',
    name: 'Empanada Mendoza',
    category: 'Italian',
    image: 'empanada-mendoza.png',
    price: 17,
  },
  {
    id: 'Italian6',
    name: 'Lechon',
    category: 'Italian',
    image: 'lechon.png',
    price: 18.99,
  },
  {
    id: 'Salad3',
    name: 'Double Pleasure Salad',
    category: 'Salad',
    image: 'double-pleasure-salad.jpeg',
    price: 13.003,
  },
  {
    id: 'Pizza13',
    name: 'Salami Finocchiona',
    category: 'Pizza',
    image: 'salami-finocchiona.jpeg',
    price: 16.5,
  },
  {
    id: 'Sushi10',
    name: 'Vegetarisch Menu',
    category: 'Sushi',
    image: 'vegetarisch-menu.jpeg',
    price: 41.26,
  },
  {
    id: 'indian1',
    name: 'Butter Chicken',
    category: 'Indian',
    image: 'butter-chicken.jpeg',
    price: 14.6,
  },
  {
    id: 'Mexican4',
    name: 'Crunchy Fried Chicken Burrito',
    category: 'Mexican',
    image: 'crunchy-fried-chicken-burrito.jpeg',
    price: 20.11,
  },
  {
    id: 'Thai6',
    name: 'Pad Thai Kai',
    category: 'Thai',
    image: 'pad-thai-kai.jpeg',
    price: 19.1,
  },
  {
    id: 'Pizza3',
    name: 'Pizza Diavola',
    category: 'Pizza',
    image: 'pizza-diavola.jpeg',
    price: 12,
  },
  {
    id: 'Italian2',
    name: 'Elote',
    category: 'Italian',
    image: 'elote.png',
    price: 24,
  },
  {
    id: 'Italian1',
    name: 'CevicheT iradito',
    category: 'Italian',
    image: 'ceviche-tiradito.png',
    price: 21.5,
  },
  {
    id: 'indian2',
    name: 'Chana Masala',
    category: 'Indian',
    image: 'chana-masala.jpeg',
    price: 14.1,
  },
  {
    id: 'Italian9',
    name: 'Rib Eye',
    category: 'Italian',
    image: 'rib-eye.png',
    price: 18.99,
  },
  {
    id: 'Italian4',
    name: 'Empanada Humita',
    category: 'Italian',
    image: 'empanada-humita.png',
    price: 19,
  },
  {
    id: 'Drink3',
    name: 'Coca Cola Light 0.5L',
    category: 'Drink',
    image: 'coca-cola-light-0.5l.jpeg',
    price: 5.1,
  },
  {
    id: 'Sushi11',
    name: 'Zalm Tonjin Menu',
    category: 'Sushi',
    image: 'zalm-tonjin-menu.jpeg',
    price: 30.05555,
  },
  {
    id: 'Pizza7',
    name: 'Pizza Pikante',
    category: 'Pizza',
    image: 'pizza-pikante.jpeg',
    price: 17,
  },
  {
    id: 'Thai5',
    name: 'Pad Krapau',
    category: 'Thai',
    image: 'pad-krapau.jpeg',
    price: 17.12,
  },
  {
    id: 'Pizza8',
    name: 'Pizza Prosciutto',
    category: 'Pizza',
    image: 'pizza-prosciutto.jpeg',
    price: 15.9,
  },
  {
    id: 'Thai8',
    name: 'Tom Yam Kai',
    category: 'Thai',
    image: 'tom-yam-kai.jpeg',
    price: 18.05,
  },
  {
    id: 'indian6',
    name: 'Dal Tarka',
    category: 'Indian',
    image: 'dal-tarka.jpeg',
    price: 11.5,
  },
  {
    id: 'Salad1',
    name: 'Chicken Egg Salad',
    category: 'Salad',
    image: 'chicken-egg-salad.jpeg',
    price: 10.63,
  },
  {
    id: 'FastFood7',
    name: 'Quarter Pounder',
    category: 'Fast food',
    image: 'quarter-pounder.jpeg',
    price: 12.3,
  },
  {
    id: 'Sushi4',
    name: 'Maki California',
    category: 'Sushi',
    image: 'maki-california.jpeg',
    price: 21.05,
  },
  {
    id: 'Thai7',
    name: 'Thaise Kipsaté',
    category: 'Thai',
    image: 'thaise-kipsaté.jpeg',
    price: 20.05,
  },
  {
    id: 'Sushi3',
    name: 'Inside Out Menu',
    category: 'Sushi',
    image: 'inside-out-menu.jpeg',
    price: 26.5,
  },
  {
    id: 'FastFood6',
    name: 'Mc Chicken',
    category: 'Fast food',
    image: 'mcChicken.jpeg',
    price: 14.5,
  },
  {
    id: 'Italian10',
    name: 'Tenderloin',
    category: 'Italian',
    image: 'tenderloin.png',
    price: 17.8,
  },
  {
    id: 'Drink8',
    name: 'Water Plat 0.5L',
    category: 'Drink',
    image: 'water-plat-0.5l.jpeg',
    price: 3.49,
  },
  {
    id: 'Pizza10',
    name: 'Pizza Tartufo',
    category: 'Pizza',
    image: 'pizza-tartufo.jpeg',
    price: 22.4,
  },
  {
    id: 'Drink4',
    name: 'Coca Cola Zero 0.5L',
    category: 'Drink',
    image: 'coca-cola-zero-0.5l.jpeg',
    price: 5.15,
  },
  {
    id: 'Sushi13',
    name: 'Zushi Maki',
    category: 'Sushi',
    image: 'zushi-maki.jpeg',
    price: 27.39,
  },
  {
    id: 'Pizza4',
    name: 'Pizza Falanga',
    category: 'Pizza',
    image: 'pizza-falanga.jpeg',
    price: 21.2,
  },
  {
    id: 'Italian3',
    name: 'Empanada Aji',
    category: 'Italian',
    image: 'empanada-aji.png',
    price: 18,
  },
  {
    id: 'Sushi7',
    name: 'Sashimi Menu Zalm',
    category: 'Sushi',
    image: 'sashimi-menu-zalm.jpeg',
    price: 29.89,
  },
  {
    id: 'Thai4',
    name: 'Koeng Nam Man Hoi',
    category: 'Thai',
    image: 'koeng-nam-man-hoi.jpeg',
    price: 15.21,
  },
  {
    id: 'Pizza9',
    name: 'Pizza Salmone',
    category: 'Pizza',
    image: 'pizza-salmone.jpeg',
    price: 16,
  },
  {
    id: 'Pizza2',
    name: 'Pizza Calabrese',
    category: 'Pizza',
    image: 'pizza-calabrese.jpeg',
    price: 14.99,
  },
  {
    id: 'FastFood9',
    name: 'Veggie Crispy Chicken Honey Mustard',
    category: 'Fast food',
    image: 'veggie-crispy-chicken-honey-mustard.jpeg',
    price: 20.5,
  },
  {
    id: 'indian10',
    name: 'Vegetable Samosa',
    category: 'Indian',
    image: 'vegetable-samosa.jpeg',
    price: 20.11,
  },
  {
    id: 'Sushi8',
    name: 'Sushi Mix',
    category: 'Sushi',
    image: 'sushi-mix.jpeg',
    price: 33.56,
  },
  {
    id: 'Thai10',
    name: 'Viskoekjes',
    category: 'Thai',
    image: 'viskoekjes.jpeg',
    price: 15.24,
  },
  {
    id: 'Mexican1',
    name: 'Al Pastor Pork Burrito',
    category: 'Mexican',
    image: 'al-pastor-pork-burrito.jpeg',
    price: 17,
  },
  {
    id: 'Sushi6',
    name: 'Nigiri Menu',
    category: 'Sushi',
    image: 'nigiri-menu.jpeg',
    price: 34.099,
  },
];
